apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2019-10-12T06:50:34Z
  labels:
    name: simple-webapp
  name: simple-webapp-1
spec:
  containers:
  - image: kodekloud/webapp-delayed-start
    name: simple-webapp
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /live
        port: 8080
      initialDelaySeconds: 80
      periodSeconds: 1
