apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: webapp
    version: "v1"
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: suhasmalusare/nodeapp:01
          ports:
            - containerPort: 8080
