apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nodeapp
    ver: "v1"
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nodeapp
  template:
    metadata:
      labels:
        run: nodeapp
        ver: "v1"
    spec:
      containers:
        - image: suhasmalusare/nodeapp:01
          imagePullPolicy: IfNotPresent
          name: nodeapp
