apiVersion: v1
kind: Service
metadata:
  labels:
    run: nodeapp
  name: nodeapp-lb-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: nodeapp
    ver: "v1" # For Blue
  #    ver: "v2"     # For green
  type: LoadBalancer
