apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-persistent-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: nfs01
    path: /html

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
spec:
  accessModes:
   - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: nfs01
    path: /mysql
