apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysql
    tier: db
  name: wordpress-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
  type: ClusterIP
status:
  loadBalancer: {}
