apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: wordpress
    tier: app
  name: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      run: wordpress
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
               name: mysql-pass
               key: password
        image: wordpress
        name: wordpress
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-persistent-storage 
