apiVersion: v1
kind: PersistentVolume
metadata:
   name: wordpress-persistent-storage
spec:
   accessModes:
     - ReadWriteMany
   nfs:
     path: /html
     server: nfs01
   capacity:
     storage: 1Gi
