apiVersion: v1
kind: PersistentVolume
metadata:
   name: mysql-persistent-storage
spec:
   accessModes:
     - ReadWriteMany
   nfs:
     path: /mysql
     server: nfs01
   capacity:
     storage: 1Gi
