apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-storage
  labels:
     pv: mysql
spec:
  accessModes:
     - ReadWriteMany
  capacity:
     storage: 1Gi
  hostPath:
     path: /var/logs
     type: Directory
