apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox-echo
      args:  
       - /bin/sh
       - -c
       - echo hello; sleep 3600

    - image: busybox
      name: busybox-sleep
      args:
       - /bin/sh
       - -c 
       - echo Hell0_2; sleep 3600
